### ISSUE TITLE
update setup.cfg according to refactor

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ComputationalMechanics/ContactMechanics#2]
Or do we use versioneer.py at all ?

**Comment by pastewka** [comment]
No, no longer. We use `setuptools_scm` now.

**Comment by AntoineSIMTEK** [comment]
So we should just remove setup.cfg, right ?

**Comment by pastewka** [comment]
Closed with f259dd82b26e45d12d463c6f4e55b6c2e2192794

**Comment by pastewka** [comment]
I just removed those
